### ISSUE TITLE
Crear la clase que envuelve a la Conexión con la base de datos (MySQL)

### ISSUE THREAD

**Issue by SantiPMendoza** [xRandom-DAM/OnlyZoo#36]

**Comment by manuelmsni** [comment]
He implementado la clase DBDonnection para gestionar la conexión a la base de datos de docker.

He añadido una clase Constants.

He añadido una carpeta para poner en ella clases que solo se usen durante el desarrollo (Development), dentro de ella he creado una carpeta para testear (tests), dentro de esta la clase Test, que registra la información de los tests y la clase TestConnection que testea si la conexión a la base de datos funciona, (para ver el resultado de los tests, tras ejecutar el programa, buscad el archivo Test.log en OnlyZoo/bin/Debug/net6.0-windows/development)
